// <auto-generated />
namespace ShoppingProjectA.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class removedkeyqualifier : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removedkeyqualifier));
        
        string IMigrationMetadata.Id
        {
            get { return "202103200801451_removedkeyqualifier"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
